<?php
/**
 * @file
 *
 * Hook implementations & general functions.
 */

/**
 * Implements hook_menu().
 */
function ptest_menu() {
  return array(
    'test-popup-forms' => array(
      'type' => MENU_NORMAL_ITEM,
      'title' => 'Test popup forms',
      'page callback' => 'ptest_page',
      'access callback' => TRUE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function ptest_theme() {
  return array(
    'ptest_example_page' => array(
      'template' => 'ptest-example-page',
    ),
  );
}

/**
 * Implements hook_popup_forms_data().
 */
function ptest_popup_forms_data() {
  return array(
    'ptest_simple_form' => array(
      'close buttons' => array('edit-submit'),
      'title' => t('Simple form'),
      'file' => drupal_get_path('module', 'ptest') . '/ptest.forms.inc',
    ),
    'ptest_simple_form2' => array(
      'close buttons' => array('edit-submit'),
      'cancel elements' => array('input[id="edit-cancel"]'),
      'file' => drupal_get_path('module', 'ptest') . '/ptest.forms.inc',
      'title' => t('Form with the cancel button and argument'),
      'form arguments' => array('text' => 'default text value'),
    ),
  );
}

/**
 * Page callback of the test page.
 */
function ptest_page() {
  popup_forms_parent_js();
  drupal_add_js(drupal_get_path('module', 'ptest') . '/ptest.js');
  return theme('ptest_example_page');
}
