<?php 

/**
 *@file
 * ajax_link_module
 * Helps PM development.
 *\
/**
 * Implements hook_menu().
 */
function ajax_test_menu() {
  $items = array();
 
  $items['ajax-test'] = array(
    'title' => 'Ajax Test',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'ajax_link_page',
    'access arguments' => array('access content'),
  );
 
  $items['my-ajax-test/%'] = array(
    'title' => 'Ajax test callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'ajax_link_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  
   
  return $items;
}
/**
 * Callback function that displays a simple Ajax powered link.
 */





 
function ajax_link_page() {
  return array( 
      array(
        '#type' => 'link',
        '#title' => t('Ajax Link'),
        '#href' => 'my-ajax-test/nojs',
        '#prefix' => '<div id="ajax-link">',
        '#suffix' => '</div> ',
        '#ajax' => array(
          'effect' => 'fade',
        ),
    ),  
      array(
        '#type' => 'textfield',
        '#title' => t('SOME ELEMENT'),
        '#value' => t('SOMETEXTSOMETEXTSOMETEXTSOMETEXTSOMETEXT'),
        '#prefix' => '<div id="text_area_id">',
        '#suffix' => '<p id="ajax-display"></p></div>',
        '#ajax' => array(
          'effect' => 'fade',
        ),
     ),
  );
}
  
  /**
 * Ajax callback to display the current time.
 */
function ajax_link_callback($ajax) {
  // Do any database queries, processing, etc.
  $time = t('The current time is: !time', array('!time' => date('Y-m-d H:i:s')));
 
  if ($ajax == 'ajax') {
    $commands = array();
    // Ajax command to replace the #ajax-display element with the current time.
    $commands[] = ajax_command_replace('#ajax-display', "<p id='ajax-display'>" . $time . "</p>");
    // Add a visual "changed" marker to the '#ajax-display' element.
    $commands[] = ajax_command_changed('#ajax-display');
    // Trigger our ajax_link jQuery plugin.
    $commands[] = ajax_command_invoke(NULL, "ajax_link");
 
    // Menu 'page callback' and #ajax['callback'] functions are supposed to
    // return render arrays. If returning an Ajax commands array, it must be
    // encapsulated in a render array structure.
    ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
  }
  else {
    // No ajax, just display the time on a page using renderable array.
    return array(
      '#markup' => $time,
    );
  }
}