<?php 
/*
 * impelements hook_theme 
 */
function theme_module_theme() {
  return array(
      'custom_theme_hook' => array(
          'variables' => array('parameters' => NULL),
      ),
        'breadcrumb' => array(
          'variables' => array('parameters' => NULL),
      ),
  );
}
function theme_custom_theme_hook($variables) { 
    $output = null;
    $variables['parameters'] = $output;
    $output = '<div id="">
        <ul>
        <li><a href="#">link 1</a></li>
        <li><a href="#">link 2</a></li>
        <li><a href="#">link 3</a></li>
        <li><a href="#">link 4</a></li>
        <li><a href="#">link 5</a></li>
        </ul>
</div>';
   
    return $output;
}
 